name: Periodic health check

on:
  schedule:
    - cron: '20 9 * * *'

jobs:
  simple_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://stark-dawn-46433.herokuapp.com/health
          follow-redirect: no # Optional, defaults to "no"
          max-attempts: 3 # Optional, defaults to 1
          retry-delay: 5s # Optional, only applicable to max-attempts > 1
          retry-all: no # Optional, defaults to "no"
