name: Hello World!

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize] # on open and update

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: >
          echo "Hello World!"
      - name: Time
        run: |
          date
      - name:
        run: |
          ls -l
