name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize] # on open and update

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1 # actions are like functions
        with:
          node-version: '12.x'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: heroku deployment
        if: github.event_name == 'push' && contains(join(github.event.commits.*.message) , '#skip') == false
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'stark-dawn-46433' #Must be unique in Heroku
          heroku_email: 'kratosshadab@gmail.com'
          healthcheck: 'https://stark-dawn-46433.herokuapp.com/health'
          checkstring: 'ok'
          rollbackonhealthcheckfailed: true

      - name: build notification success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,job,took # selectable (default: repo,message)
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `A new version deployed to https://stark-dawn-46433.herokuapp.com/ (${{process.env.AS_REF}}) by ${{ process.env.AS_AUTHOR }} build took ${{ process.env.AS_TOOK }}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

      - name: build notification failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

  versioning_pipeline: # job
    runs-on: ubuntu-18.04
    steps: # step
      - uses: actions/checkout@v2 # get repository
      - name: Bump version and push tag
        if: contains(join(github.event.commits.*.message) , '#skip') == false && (github.event_name == 'pull_request') == false
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

